### PR TITLE
Bump websocket to ws 7.4.5

### PR DESCRIPTION
**Pull request by trasherdk**
ws latest version.
keep repo_token to myself.
Add script to run test separate.
Get eslint to stop bitching.

### CODE REVIEW

**Comment by mkozjak** [comment]
Hello, @trasherdk, thanks for the PR!

There's a failing test going on on `trasherdk:ws-7.4.5`. Can you check out what the issue is?

```
1) Client
       .login
         should succeed if correct credentials were provided:
     TypeError: Cannot read property 'code' of undefined
      at /private/tmp/rpc-websockets/test/client.spec.js:342:37
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by trasherdk** [comment]
Okay. Got it.

The `client.login()` return true/false, and not a status code :cactus:

**Comment by mkozjak** [comment]
Are tests passing on your end?

```
    .login
      ✓ should throw if wrong credentials were provided
AssertionError: expected undefined to be true
    at /private/tmp/rpc-websockets/test/client.spec.js:342:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  showDiff: true,
  actual: undefined,
  expected: true
}
      1) should succeed if correct credentials were provided
```

```
  1) Client
       .login
         should succeed if correct credentials were provided:
     AssertionError: expected undefined to be true
      at /private/tmp/rpc-websockets/test/client.spec.js:342:43
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by trasherdk** [comment]
Yes, no problem. Did you do the `npm ci` thing first?
```
$ npm run test

> rpc-websockets@7.4.11 pretest
> npm run-script build


> rpc-websockets@7.4.11 build
> tsc && mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.ts' && babel ./build-ts -d ./dist --copy-files && browserify -s RPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 8 files with Babel (1976ms).

> rpc-websockets@7.4.11 test
> mocha --exit test/*spec.js



  Client
    ✓ should return a new instance
    ✓ should get registered methods from server
    .connect
      ✓ should explicitly connect to server
    .call
      ✓ should call an RPC method without parameters and receive a valid response
      ✓ should call an RPC method with parameters and receive a valid response
      ✓ should call an RPC method and receive a valid response when RPC method returns a circular object
      ✓ should forward ws options to ws.send
      ✓ should correctly throw if nonexistent method called
      ✓ should throw Error on reply timeout
      ✓ should call a protected RPC method and receive an error
      ✓ should call a protected RPC method and receive a response
    .login
      ✓ should throw if wrong credentials were provided
      ✓ should succeed if correct credentials were provided
    .notify
      ✓ should send a notification
    .subscribe
      ✓ should subscribe to an event
      ✓ should subscribe to multiple events
      ✓ should throw Error if event is not registered
      ✓ should throw an error if event name not provided
      ✓ should receive an event with no values
      ✓ should receive an event with a single value
      ✓ should receive an event with multiple values
      ✓ should receive an event with a single object value
      ✓ should receive an event with circular object
    .unsubscribe
      ✓ should unsubscribe from an event
      ✓ should unsubscribe from multiple events
      ✓ should throw an error if event name not provided
    .namespace
      ✓ should subscribe to an event
      ✓ should subscribe to multiple events
      ✓ should receive an event from a joined namespace
      ✓ should receive params from an event correctly
    .close
      ✓ should close a connection gracefully

  Server
    ✓ should return a new instance
    ✓ should forward throw an error from 'ws' if no params object is passed
    ✓ .register
    ✓ .register.protected
    ✓ .register.public
    ✓ .setAuth
    ✓ .event
    ✓ .event.protected
    ✓ .event.public
    ✓ .eventList
    ✓ .emit
    ✓ .namespace
    ✓ .namespaceMethod
    ✓ .namespaceList
    ✓ .closeNamespace
    ✓ .createError
    ✓ .close
    WebSocket API
      # connection
        ✓ should connect client with a custom socket id
      # single rpc request
        ✓ should return a valid response using single parameter
        ✓ should return a valid response using positional parameters
        ✓ should return a valid response using named parameters
        ✓ should return a valid response with circular object references
        ✓ should respond with -32601 when calling a missing method
        ✓ should respond with -32700 when called with invalid JSON
        ✓ should respond with -32600 when request data is null
        ✓ should respond with -32600 when called with invalid method name in JSON-RPC 2.0 Request object
        ✓ should respond with -32600 when called with invalid params type in JSON-RPC 2.0 Request object
        ✓ should return a valid error if callback threw with .error
        ✓ should return a valid error if callback threw with JavaScript's Error
      # batch rpc request
        ✓ should return a valid response
        ✓ should respond with -32700 when called with invalid JSON
        ✓ should respond with -32600 when called with an empty array
        ✓ should respond with -32600 when called with invalid non-empty array
        ✓ should respond with -32600 when called with invalid data
        ✓ should receive all notifications
      # notification
        ✓ should receive a notification
      # event
        ✓ should respond with -32000 if event name not provided
        ✓ should subscribe a user to an event
        ✓ should emit an event with no values to subscribed clients
        ✓ should emit an event with single value to subscribed clients
        ✓ should emit an event with multiple values to subscribed clients
        ✓ should emit an event with circular objects to subscribed clients
        ✓ should unsubscribe a user from an event
      # login
        ✓ should respond with -32604 if params not provided
        ✓ should respond with false if login failed
        ✓ should respond with -32605 when called without being authorized
        ✓ should respond with true if login successful
        ✓ should return a valid response if authorized


  79 passing (417ms)

mogens@ghost-node:~/local/github/rpc-websockets$ git status
On branch ws-7.4.5
```

**Comment by trasherdk** [comment]
BTW. I'm on latest node LTS.
```
$ node -v && npm -v
v14.17.0
7.13.0
```

**Comment by mkozjak** [comment]
Yup, npm ci && npm it gave me this:

```
 > npm ci && npm it

added 871 packages, and audited 872 packages in 25s

found 0 vulnerabilities

up to date, audited 872 packages in 3s

found 0 vulnerabilities

> rpc-websockets@7.4.11 pretest
> npm run-script build


> rpc-websockets@7.4.11 build
> tsc && mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.ts' && babel ./build-ts -d ./dist --copy-files && browserify -s RPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 8 files with Babel (6529ms).

> rpc-websockets@7.4.11 test
> mocha --exit test/*spec.js



  Client
    ✓ should return a new instance
    ✓ should get registered methods from server
    .connect
      ✓ should explicitly connect to server
    .call
      ✓ should call an RPC method without parameters and receive a valid response
      ✓ should call an RPC method with parameters and receive a valid response
      ✓ should call an RPC method and receive a valid response when RPC method returns a circular object
      ✓ should forward ws options to ws.send
      ✓ should correctly throw if nonexistent method called
      ✓ should throw Error on reply timeout
      ✓ should call a protected RPC method and receive an error
      ✓ should call a protected RPC method and receive a response
    .login
      ✓ should throw if wrong credentials were provided
AssertionError: expected undefined to be true
    at /private/tmp/rpc-websockets/test/client.spec.js:342:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  showDiff: true,
  actual: undefined,
  expected: true
}
      1) should succeed if correct credentials were provided
    .notify
      ✓ should send a notification
    .subscribe
      ✓ should subscribe to an event
      ✓ should subscribe to multiple events
      ✓ should throw Error if event is not registered
      ✓ should throw an error if event name not provided
      ✓ should receive an event with no values
      ✓ should receive an event with a single value
      ✓ should receive an event with multiple values
      ✓ should receive an event with a single object value
      ✓ should receive an event with circular object
    .unsubscribe
      ✓ should unsubscribe from an event
      ✓ should unsubscribe from multiple events
      ✓ should throw an error if event name not provided
    .namespace
      ✓ should subscribe to an event
      ✓ should subscribe to multiple events
      ✓ should receive an event from a joined namespace
      ✓ should receive params from an event correctly
    .close
      ✓ should close a connection gracefully

  Server
    ✓ should return a new instance
    ✓ should forward throw an error from 'ws' if no params object is passed
    ✓ .register
    ✓ .register.protected
    ✓ .register.public
    ✓ .setAuth
    ✓ .event
    ✓ .event.protected
    ✓ .event.public
    ✓ .eventList
    ✓ .emit
    ✓ .namespace
    ✓ .namespaceMethod
    ✓ .namespaceList
    ✓ .closeNamespace
    ✓ .createError
    ✓ .close
    WebSocket API
      # connection
        ✓ should connect client with a custom socket id
      # single rpc request
        ✓ should return a valid response using single parameter
        ✓ should return a valid response using positional parameters
        ✓ should return a valid response using named parameters
        ✓ should return a valid response with circular object references
        ✓ should respond with -32601 when calling a missing method
        ✓ should respond with -32700 when called with invalid JSON
        ✓ should respond with -32600 when request data is null
        ✓ should respond with -32600 when called with invalid method name in JSON-RPC 2.0 Request object
        ✓ should respond with -32600 when called with invalid params type in JSON-RPC 2.0 Request object
        ✓ should return a valid error if callback threw with .error
        ✓ should return a valid error if callback threw with JavaScript's Error
      # batch rpc request
        ✓ should return a valid response
        ✓ should respond with -32700 when called with invalid JSON
        ✓ should respond with -32600 when called with an empty array
        ✓ should respond with -32600 when called with invalid non-empty array
        ✓ should respond with -32600 when called with invalid data
        ✓ should receive all notifications
      # notification
        ✓ should receive a notification
      # event
        ✓ should respond with -32000 if event name not provided
        ✓ should subscribe a user to an event
        ✓ should emit an event with no values to subscribed clients
        ✓ should emit an event with single value to subscribed clients
        ✓ should emit an event with multiple values to subscribed clients
        ✓ should emit an event with circular objects to subscribed clients (44ms)
        ✓ should unsubscribe a user from an event
      # login
        ✓ should respond with -32604 if params not provided
        ✓ should respond with false if login failed
        ✓ should respond with -32605 when called without being authorized
        ✓ should respond with true if login successful
        ✓ should return a valid response if authorized


  78 passing (1s)
  1 failing

  1) Client
       .login
         should succeed if correct credentials were provided:
     AssertionError: expected undefined to be true
      at /private/tmp/rpc-websockets/test/client.spec.js:342:43
      at processTicksAndRejections (internal/process/task_queues.js:95:5)



npm ERR! code 1
npm ERR! path /private/tmp/rpc-websockets
npm ERR! command failed
npm ERR! command sh -c mocha --exit test/*spec.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-05-18T13_32_31_904Z-debug.log

 >
```

node and npm versions:
```
 > npm --version
7.11.2
 > node --version
v14.17.0
```

**Comment by trasherdk** [comment]
WTF. Now I'm getting the same error ?????

**Comment by trasherdk** [comment]
Got it. `rpc-websockets/src/lib/client.ts` the `login` function does not return anything.
```
    async login(params: IWSRequestParams)
    {
        const resp = await this.call("rpc.login", params)

        if (!resp)
            throw new Error("authentication failed")

        return resp <=== this is missing
    }
```

**Review by mkozjak — APPROVED** [review]

**Pull request merged**
