### PR TITLE
Send notifications on next tick

### PR DESCRIPTION
**Pull request by jstarry**
Fixes: https://github.com/elpheria/rpc-websockets/issues/83

This is a quick and dirty fix for the race condition. Feel free to go with another approach

### CODE REVIEW

**Comment by mkozjak** [comment]
@jstarry thanks, looks good! I'm thinking we should add a nextTick library that can be used across platforms (node.js, web).
https://github.com/medikoo/next-tick

**Comment by jstarry** [comment]
Yes, good call. Want me to close this PR? Your branch looks good to me

**Comment by mkozjak** [comment]
@jstarry - no, just merge my pull request in your fork and I’ll merge this PR.

**Comment by jstarry** [comment]
@mkozjak done. Do you mind pushing out a patch release for this fix? Not a big rush, but would be nice

**Review by mkozjak — APPROVED** [review]

**Comment by mkozjak** [comment]
@jstarry: thanks for the PR - the feature is available in 7.1.0!

**Comment by jstarry** [comment]
@mkozjak thanks for the quick turn around!

**Pull request merged**
