### PR TITLE
Add protected events

### LINKED ISSUE #78: Cannot protect event subscription
Hi,

I really like this library, and the auth/protected layer it puts on top, however this protection doesn't extend to the event extension, is there a reason why this is like it is? If not it would be great to see added.

### PR DESCRIPTION
**Pull request by james-ct**
Fixes #78, as requested @mkozjak 😄

### CODE REVIEW

**Comment by james-ct** [comment]
Yeah I agree, I had created an interface named `IAuthentication` with those two methods, but ended up reverting to what was already there.

**Comment by mkozjak** [comment]
Fair enough. I’m thinking maybe we should rename RPCMethod to Method and add a new type called Event which will, for now, have same properties as current RPCMethod. That way we can have different possible properties/members in future. What do you think about that one?

**Comment by james-ct** [comment]
Sounds good, I'm happy for you to make the change here and merge it or I can do it in a few hours time. If I don't see any movement here I'll do it.

**Comment by james-ct** [comment]
It looks like I had left the interface in there, fixed that up though.

**Comment by mkozjak** [comment]
Amazing work, @james-ct! Merging now.

**Comment by james-ct** [comment]
@mkozjak any plans for when this might be released?

**Comment by mkozjak** [comment]
@james-ct released a moment ago in 5.3.0 :)

**Comment by james-ct** [comment]
Looks like the code wasn't rebuilt and committed (into the dist folder)? `npm install` still gives me the previous version built files. Perhaps we should have done that on the branch?

**Comment by mkozjak** [comment]
Yup, we should’ve. Releasing it in a patch soon.

**Comment by mkozjak** [comment]
Done, it's in 5.3.1. Can you test?

**Comment by james-ct** [comment]
All good :+1: thanks!

**Pull request merged**
